### ISSUE TITLE
러프한 초기 구상

### ISSUE THREAD

**Issue by ca1af** [ThugDev/PR-Deliver#1]
# 회원 : Member

### 회원가입
- 회원은 깃허브 OAuth2 를 이용해서 회원 가입, 로그인을 할 수 있다.
- 회원이 가지는 정보는 다음과 같다
1. 깃허브 아이디
2. 추가 회원가입 절차를 통해서 등록할 repository, 등록할 메신저(DISCORD, SLACK...) 웹훅 url

---
# 메신저

### 메신저 등록
- 회원은 메신저 웹훅을 등록한다.
- 서버는 등록한 메신저 웹훅에 인증 url 을 발송한다. 이 Url 로 사용자가 요청을 보내면 메신저 등록이 완료된다.

### 메신저 비활성화
- 등록한 메신저를 비활성화 상태로 전환한다.
- 비활성화된 메신저에는 웹훅 알림이 발송되지 않는다.

### 메신저 메시지 수정
- 메신저에 발송할 메시지를 사용자가 원하는대로 수정 할 수 있다.

---

# 레포지토리

- 사용자가 웹훅을 통해 레포지토리를 등록한다
- 등록된 레포지토리는 collaborator 정보를 들고있다.

---
# 콜라보레이터

- 레포지토리의 구성원들
- 구성원들은 깃허브 아이디와 메신저 타입 (N개), 그리고 메신저별 별명을 (N개) 가진다.

---

### 메신저 별명 (따로 설정해주자 그냥)

- 메신저 타입
- 메신저 아이디
- 깃허브 아이디

를 가진다.

- 유저가 등록하려고 할 때, 이미 등록되어있는 아이디는 불러와서 보여준다.

**Comment by 55555-Jyeon** [comment]
#### 현재 YEOGI 프로젝트에서 사용되고 있는 모습 (Discord channel)

<img width="50%" alt="Screenshot 2024-08-09 at 3 40 32 PM" src="https://github.com/user-attachments/assets/0bfedde4-ef0b-4efe-8e4a-98dc6ddca88d">

**Comment by 55555-Jyeon** [comment]
## 🧐 Question

제가 이해한게 맞는지 확인 부탁드립니다.

<br />

웹사이트의 역할 : "여러 명의 개발자가 프로젝트를 진행할 때 PR을 생성하면 랜덤으로 리뷰어를 설정해 등록한 채널로 알림을 보내준다."

<br />

1. 유저가 개발할 페이지를 통해 깃허브로 로그인을 한다.
2. 프로젝트를 등록한다. 


2번에서 프로젝트를 등록할 때 받아야 할 정보 : 레포 주소, 채널 주소, 동료의 깃허브 계정

<br />
