### ISSUE TITLE
[2024.08.12] 20:30 기획 관련 미팅

### ISSUE THREAD

**Issue by 55555-Jyeon** [ThugDev/PR-Deliver#3]
디자이너 분께 전달할 기획 기반 페이지별 내용 정리 진행할 피그마 링크 첨부합니다.

피그마 링크 : https://www.figma.com/design/zBv18pZAnySUtNNVkK1AyA/PR-deliver?node-id=0-1&t=OjhSmcyC20KJoom6-1

**Comment by 55555-Jyeon** [comment]
#### wireframe

간략하게 페이지마다 들어갈 내용이랑 내용에 따라 상상되는 레이아웃 잡아봤습니다.
확인 후 생각하신 플로우가 맞는지 확인 부탁드립니다! 🧐

👩🏻‍💻 ㅣ @ca1af , @ijimlnosk 

전원 확인하면 디자이너 분께 해당 링크, 디스코드 링크 송부드리겠습니다.
다같이 회의 진행할 수 있는 시간대는 이번 주 내로 다시 한 번 잡아보겠습니다!

<img width="1123" alt="Screenshot 2024-08-12 at 9 25 18 PM" src="https://github.com/user-attachments/assets/352f4dbd-9fce-4fab-a02c-fead685a1bb3">

**Comment by ijimlnosk** [comment]
확인했습니다
